"%prod":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import.sql
    swagger-ui:
      always-include: true

mp:
  messaging:
    outgoing:
      todocompletions:
        connector: smallrye-kafka
        topic: todocompletions

"%test":
  mp:
    messaging:
      outgoing:
        todocompletions:
          connector: smallrye-in-memory
          merge: true