name: Build and test

env:
  MANDREL_VERSION: "23.0.0.0-Final"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.adoc'
      - 'quarkus-todo/initialCode/**'
      - 'quarkus-todo/demo/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.adoc'
      - 'quarkus-todo/initialCode/**'
      - 'quarkus-todo/demo/**'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - quarkus-todo
          - quarkus-todo-listener
    name: jvm-build-test-${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: build-test
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0

  native-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - quarkus-todo
          - quarkus-todo-listener
    name: native-build-test-${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache and restore Mandrel distro
        id: check-mandrel-cache
        uses: actions/cache@v3
        with:
          path: mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz
          key: mandrel-distro-${{ env.MANDREL_VERSION }}-17

      - name: Download Mandrel
        if: steps.check-mandrel-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${MANDREL_VERSION}/mandrel-java17-linux-amd64-${MANDREL_VERSION}.tar.gz"
          wget -q -O mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz $download_url

      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz
          java-version: 17
          architecture: x64
          cache: maven

      - name: build-test
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify -Pnative -Dquarkus.http.host=0.0.0.0
